# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFvdpB7qzyRh5fnP3nc0VKLUadtwLwyH
"""

x1,y1 =map(int, input().split())
x2,y2 =map(int, input().split())

if 0<=x2<=7 and 0<=y2<= 7:
  if checkerboard[x2][y2]==0:
    if abs(x2-x1)<=1 and abs(y2-y1)<=1:
      print("Yes")
    else:
      print("No")
  else:
    print("No")
else:
  print("No")


#X2==X1+1 and y2==y2+2